name: flutter_app
description: A new Flutter application for women who code cincinnati

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dart
  rxdart: ^0.24.0
  http: ^0.12.0+4
  json_annotation: ^3.0.0
  async: 2.5.0-nullsafety.1
  provider: ^4.0.3
  equatable: ^1.1.0

  # flutter
  url_launcher: ^5.4.5
  cupertino_icons: ^0.1.3
  package_info: ^0.4.0+13
  font_awesome_flutter: 8.10.0
  flutter_staggered_grid_view: 0.3.2
  build_runner: 1.10.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.0

flutter_icons:
  image_path: "assets/wwcode-launcher-icon.png"
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/cincinnati_header.jpg